#---------------------------------------------------------------------------------

# Common source folders for both arm7/arm9

export COMMON_SOURCES	:=	../source ../source/ntr ../source/ntr/extra ../source/ntr/arm
